// <auto-generated />
using System;
using E_commerce.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace E_commerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514135951_hasData2")]
    partial class hasData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("E_commerce.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hogar y Cocina"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deportes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Libros"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Belleza y Cuidado Personal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Automotriz"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jardín y Exteriores"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Salud y Bienestar"
                        });
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExpress")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 14, 10, 30, 0, 0, DateTimeKind.Utc),
                            IsExpress = false,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 15, 14, 45, 0, 0, DateTimeKind.Utc),
                            IsExpress = true,
                            Status = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("E_commerce.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 699.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 14.95m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 79.99m
                        });
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Smartphone X1",
                            Price = 699.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Televisor 4K 55”",
                            Price = 499.50m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Camiseta Deportiva",
                            Price = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "Juego de Sábanas King",
                            Price = 59.90m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Name = "Pelota de Fútbol Oficial",
                            Price = 19.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Name = "Novela “El Misterio”",
                            Price = 14.95m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Name = "Set Maquillaje Profesional",
                            Price = 49.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Name = "Lego Castillo Medieval",
                            Price = 89.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            Name = "Aceite Motor 5W-30",
                            Price = 24.50m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            Name = "Silla Plegable Jardín",
                            Price = 79.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 10,
                            Name = "Pulsera Inteligente Fit",
                            Price = 129.99m,
                            Stock = 22
                        });
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("E_commerce.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Order", b =>
                {
                    b.HasOne("E_commerce.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("E_commerce.Domain.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerce.Domain.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Product", b =>
                {
                    b.HasOne("E_commerce.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.User", b =>
                {
                    b.HasOne("E_commerce.Domain.Models.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("E_commerce.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
